name: Update Badges

on:
  workflow_call:
    inputs:
      default-branch:
        description: 'Default branch name'
        default: main
        required: false
        type: string
      python-version:
        description: 'Python version to use for badge updates'
        default: '3.10'
        required: false
        type: string
    secrets:
      SERVICE_TOKEN:
        required: true

jobs:
  update_badges:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.default-branch }}
        fetch-depth: 0
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Pull latest changes
      run: git pull origin ${{ inputs.default-branch }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: | 
        python -m pip install -e .[dev] --no-cache-dir
    - name: Get Python version and Update README.md
      run: |
        python_version=$(grep "requires-python" pyproject.toml | grep -o ">=[^\"]*")
        python_badge=$(grep -o 'python-[^)]*' README.md)
        new_python_badge="python-$python_version-blue?logo=python"
        sed -i "s/$python_badge/$new_python_badge/g" README.md
    - name: Get interrogate values and Update README.md
      run: |
        interrogate_val=$(interrogate . | grep -o 'actual: [0-9]*\.[0-9]*' | awk '{print $2}')
        interrogate_badge=$(grep -o 'interrogate-[^)]*' README.md)
        if (( $(echo "$interrogate_val >= 90.00" | bc -l) )); then
            new_interrogate_badge="interrogate-$interrogate_val%25-brightgreen"
        elif (( $(echo "$interrogate_val < 80.00" | bc -l) )); then
            new_interrogate_badge="interrogate-$interrogate_val%25-red"
        else
            new_interrogate_badge="interrogate-$interrogate_val%25-yellow"
        fi
        sed -i "s/$interrogate_badge/$new_interrogate_badge/g" README.md
    - name: Get Coverage values and Update README.md
      run: |
        coverage run -m unittest discover
        coverage_val=$(coverage report | grep "^TOTAL" | grep -o '[0-9]\+%' | grep -o '[0-9]\+')
        coverage_badge=$(grep -o "coverage-[^?]*" README.md)
        if (( $(echo "$coverage_val >= 90.00" | bc -l) )); then 
            new_coverage_badge="coverage-$coverage_val%25-brightgreen"
        elif (( $(echo "$coverage_val < 80.00" | bc -l) )); then
            new_coverage_badge="coverage-$coverage_val%25-red"
        else
            new_coverage_badge="coverage-$coverage_val%25-yellow"
        fi
        sed -i "s/$coverage_badge/$new_coverage_badge/g" README.md
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "ci: update badges [skip actions]"
        add: '["README.md"]'
